
const app=document.getElementById("app");
const IMG={home:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=88",city:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=88",calendar:"https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?auto=format&fit=crop&w=1600&q=88",couple:"https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=88",family:"https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=1200&q=88",friends:"https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=88",solo:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=88",food:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=88",culture:"https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=88",nature:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=88",wellness:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=88",sport:"https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=88",night:"https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?auto=format&fit=crop&w=1200&q=88",workshop:"https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=88",market:"https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1200&q=88",fallback:"https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=88"};
const S={step:"home",month:new Date(),start:new Date(),end:new Date(),location:{name:"Le Touquet-Paris-Plage",lat:50.5214,lng:1.5912},destInput:"",people:2,budgetTotal:200,budgetUnknown:false,answers:{who:null,vibes:[]},items:[],places:[],events:[],weather:null,program:[],agenda:JSON.parse(localStorage.getItem("dolcia_agenda")||"[]"),activeDay:"Jour 1",radius:18000,loading:false};
const VIBES=[["food","Gastronomie","Restaurants, brunchs, marchés, dégustations",IMG.food],["culture","Culture & événements","Concerts, théâtre, spectacles, expositions",IMG.culture],["workshop","Ateliers","Leroy Merlin, Cultura, IKEA, activités créatives",IMG.workshop],["market","Marchés & brocantes","Brocantes, vide-greniers, marchés nocturnes",IMG.market],["nature","Nature","Balades, plage, coucher de soleil, points de vue",IMG.nature],["wellness","Bien-être","Spa, massage, yoga, parenthèse calme",IMG.wellness],["sport","Loisirs actifs","Paddle, vélo, bowling, escape game, golf",IMG.sport],["night","Sortir","Bars, cocktails, casino, DJ, soirée",IMG.night]];
const TYPES={food:["restaurant","cafe","bakery","bar"],culture:["museum","art_gallery","movie_theater","tourist_attraction"],workshop:["home_goods_store","book_store","art_gallery","tourist_attraction"],market:["tourist_attraction","store"],nature:["park","tourist_attraction"],wellness:["spa","beauty_salon","swimming_pool"],sport:["bowling_alley","amusement_park","aquarium","zoo","golf_course"],night:["bar","night_club","casino","restaurant"]};
const KW={food:["restaurant terrasse","brunch","glacier","salon de thé","bar à vin","dégustation"],culture:["concert","théâtre","pièce de théâtre","spectacle","humour","exposition","festival"],workshop:["atelier Leroy Merlin","atelier Cultura","atelier IKEA","atelier enfant","atelier créatif","cours cuisine"],market:["brocante","vide grenier","marché nocturne","marché local","foire","salon"],nature:["coucher de soleil","balade","plage","point de vue","jardin remarquable"],wellness:["spa","massage","yoga","bien-être","hammam"],sport:["escape game","bowling","mini golf","paddle","location vélo","centre équestre"],night:["bar cocktail","concert ce soir","soirée","casino","DJ set"]};
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function save(){localStorage.setItem("dolcia_agenda",JSON.stringify(S.agenda))}
function nice(d){return d.toLocaleDateString("fr-FR",{day:"numeric",month:"short"})}
function same(a,b){return a&&b&&a.toDateString()===b.toDateString()}
function daysCount(){let a=new Date(S.start.getFullYear(),S.start.getMonth(),S.start.getDate()),b=new Date(S.end.getFullYear(),S.end.getMonth(),S.end.getDate());return Math.max(1,Math.round((b-a)/86400000)+1)}
function perDayPerson(){return S.budgetUnknown?null:Math.round((Number(S.budgetTotal)||0)/Math.max(1,S.people)/daysCount())}
function budgetText(){if(S.budgetUnknown)return"Budget libre";return `${S.budgetTotal} € total · ${S.people} pers. · env. ${perDayPerson()} €/jour/pers.`}
function top(back=true){return `<header class="top">${back?`<button class="icon" onclick="back()">←</button>`:`<div></div>`}<div class="logo">DOL<span>CIA</span></div><button class="ghost" onclick="reset()">Recommencer</button></header>`}
function bg(url){return `<div class="bg" style="background-image:url('${url}')"></div>`}
function renderHome(){app.innerHTML=`<section class="screen">${bg(IMG.home)}${top(false)}<div class="hero"><div class="eyebrow">Concierge loisirs personnel</div><h1>Arrêtez de chercher. Commencez à vivre.</h1><p>Dolcia compose votre sortie, votre journée ou votre séjour à partir de données réelles : restaurants, concerts, théâtre, ateliers, marchés, activités et pépites locales.</p><button class="gold" onclick="go('where')">Composer mon programme</button></div></section>`}
function go(step){S.step=step; if(step==="where") renderWhere(); if(step==="date") renderDate(); if(step==="who") renderWho(); if(step==="budget") renderBudget(); if(step==="vibes") renderVibes();}
function back(){if(S.step==="where")renderHome();else if(S.step==="date")renderWhere();else if(S.step==="who")renderDate();else if(S.step==="budget")renderWho();else if(S.step==="vibes")renderBudget();else renderHome()}
function reset(){S.items=[];S.program=[];renderHome()}
function renderWhere(){app.innerHTML=`<section class="screen">${bg(IMG.city)}${top()}<div class="progress"><span style="width:17%"></span></div><div class="inner step-head"><div class="eyebrow">Étape 1</div><h2>Où partons-nous ?</h2><p>Dolcia fonctionne partout : autour de vous ou dans une destination à préparer.</p></div><div class="grid"><button class="card big" onclick="useGeo()"><div class="photo" style="background-image:url('${IMG.city}')"></div><div class="shade"></div><div class="txt"><b>Autour de moi</b><small>Dolcia utilise votre position actuelle.</small></div></button><button class="card big" onclick="showDestinationInput()"><div class="photo" style="background-image:url('${IMG.calendar}')"></div><div class="shade"></div><div class="txt"><b>Choisir une destination</b><small>Ville, région ou pays. Pas de liste figée.</small></div></button></div><div id="dest"></div></section>`}
function showDestinationInput(){document.getElementById("dest").innerHTML=`<div class="searchbox"><input id="destInput" placeholder="Ex : Le Touquet, Paris, Annecy..." value="${esc(S.destInput)}" oninput="S.destInput=this.value"></div><div class="sticky"><button class="dark" onclick="renderWhere()">Retour</button><button class="gold" onclick="setDestination()">Continuer</button></div>`;setTimeout(()=>document.getElementById("destInput")?.focus(),100)}
function setDestination(){if(S.destInput.trim())S.location={name:S.destInput.trim(),lat:S.location.lat,lng:S.location.lng};go("date")}
function useGeo(){if(navigator.geolocation){navigator.geolocation.getCurrentPosition(p=>{S.location={name:"Autour de moi",lat:p.coords.latitude,lng:p.coords.longitude};go("date")},()=>go("date"),{timeout:3500})}else go("date")}
function renderDate(){app.innerHTML=`<section class="screen">${bg(IMG.calendar)}${top()}<div class="progress"><span style="width:34%"></span></div><div class="inner step-head"><div class="eyebrow">Étape 2</div><h2>Quand ?</h2><p>Impossible de proposer concerts, théâtre, ateliers ou événements sans dates.</p></div><div class="pills">${["Aujourd’hui","Demain","Ce week-end","Choisir mes dates"].map(x=>`<button class="pill" onclick="quickDate('${x}')">${x}</button>`).join("")}</div>${calendarHtml()}<div class="sticky"><button class="dark" onclick="back()">Retour</button><button class="gold" onclick="go('who')">Continuer</button></div></section>`}
function quickDate(x){let n=new Date();S.start=new Date(n);S.end=new Date(n);if(x==="Demain"){S.start.setDate(n.getDate()+1);S.end=new Date(S.start)}if(x==="Ce week-end"){let add=(6-n.getDay()+7)%7||0;S.start.setDate(n.getDate()+add);S.end=new Date(S.start);S.end.setDate(S.start.getDate()+1)}S.month=new Date(S.start.getFullYear(),S.start.getMonth(),1);renderDate()}
function calendarHtml(){let y=S.month.getFullYear(),m=S.month.getMonth(),first=new Date(y,m,1),pad=(first.getDay()+6)%7,nb=new Date(y,m+1,0).getDate();let cells="";for(let i=0;i<pad;i++)cells+=`<button class="day empty"></button>`;for(let d=1;d<=nb;d++){let dt=new Date(y,m,d),sel=same(dt,S.start)||same(dt,S.end),range=dt>S.start&&dt<S.end;cells+=`<button class="day ${sel?'sel':''} ${range?'range':''}" onclick="pickDate(${y},${m},${d})">${d}</button>`}return `<div class="calendar"><div class="calhead"><button class="icon" onclick="moveMonth(-1)">‹</button><b>${S.month.toLocaleDateString("fr-FR",{month:"long",year:"numeric"})}</b><button class="icon" onclick="moveMonth(1)">›</button></div><div class="week">${["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map(x=>`<span>${x}</span>`).join("")}</div><div class="days">${cells}</div></div>`}
function moveMonth(n){S.month=new Date(S.month.getFullYear(),S.month.getMonth()+n,1);renderDate()}
function pickDate(y,m,d){let dt=new Date(y,m,d);if(!S.start||!S.end||!same(S.start,S.end)){S.start=dt;S.end=dt}else if(dt<S.start){S.start=dt;S.end=dt}else S.end=dt;renderDate()}
function renderWho(){let opts=[["couple","En couple","Une expérience à deux",IMG.couple],["family","En famille","Rythme réaliste, enfants compris",IMG.family],["friends","Entre amis","Plus vivant, plus spontané",IMG.friends],["solo","Solo","Se faire plaisir sans compromis",IMG.solo]];app.innerHTML=`<section class="screen">${bg(IMG.couple)}${top()}<div class="progress"><span style="width:51%"></span></div><div class="inner step-head"><div class="eyebrow">Étape 3</div><h2>Avec qui ?</h2><p>Le programme change totalement selon le contexte humain.</p></div><div class="grid">${opts.map(o=>`<button class="card ${S.answers.who===o[0]?'sel':''}" onclick="S.answers.who='${o[0]}';go('budget')"><div class="photo" style="background-image:url('${o[3]}')"></div><div class="shade"></div><div class="txt"><b>${o[1]}</b><small>${o[2]}</small></div></button>`).join("")}</div></section>`}
function renderBudget(){app.innerHTML=`<section class="screen">${bg(IMG.food)}${top()}<div class="progress"><span style="width:68%"></span></div><div class="inner step-head"><div class="eyebrow">Étape 4</div><h2>Budget réel.</h2><p>Plus de budget “raisonnable” subjectif. Dolcia calcule selon la durée et le nombre de personnes.</p></div><div class="budgetbox"><label>Budget total de la sortie / du séjour</label><input type="number" value="${S.budgetTotal}" oninput="S.budgetTotal=Number(this.value);renderBudgetHint()"><div id="bh" class="budgethint">${budgetText()}</div></div><div class="budgetbox"><label>Nombre de personnes</label><input type="number" min="1" value="${S.people}" oninput="S.people=Math.max(1,Number(this.value));renderBudgetHint()"></div><div class="pills"><button class="pill ${S.budgetUnknown?'sel':''}" onclick="S.budgetUnknown=!S.budgetUnknown;renderBudget()">Je ne sais pas / libre</button><button class="pill" onclick="S.budgetTotal=100;S.budgetUnknown=false;renderBudget()">100 €</button><button class="pill" onclick="S.budgetTotal=250;S.budgetUnknown=false;renderBudget()">250 €</button><button class="pill" onclick="S.budgetTotal=500;S.budgetUnknown=false;renderBudget()">500 €</button></div><div class="sticky"><button class="dark" onclick="back()">Retour</button><button class="gold" onclick="go('vibes')">Continuer</button></div></section>`}
function renderBudgetHint(){document.getElementById("bh").textContent=budgetText()}
function renderVibes(){app.innerHTML=`<section class="screen">${bg(IMG.culture)}${top()}<div class="progress"><span style="width:85%"></span></div><div class="inner step-head"><div class="eyebrow">Étape 5</div><h2>Quelle ambiance ?</h2><p>Choisissez plusieurs envies : Dolcia composera un agenda varié.</p></div><div class="grid">${VIBES.map(v=>`<button class="card ${S.answers.vibes.includes(v[0])?'sel':''}" onclick="toggleVibe('${v[0]}')"><div class="photo" style="background-image:url('${v[3]}')"></div><div class="shade"></div><div class="txt"><b>${v[1]}</b><small>${v[2]}</small></div></button>`).join("")}</div><div class="sticky"><button class="dark" onclick="back()">Retour</button><button class="gold" onclick="compose()">Surprends-moi</button></div></section>`}
function toggleVibe(id){if(S.answers.vibes.includes(id))S.answers.vibes=S.answers.vibes.filter(x=>x!==id);else S.answers.vibes.push(id);renderVibes()}
async function compose(){renderLoading();S.items=[];S.places=[];S.events=[];S.program=[];S.loading=true;setTimeout(()=>{if(S.loading){S.loading=false;finishRender()}},4500);try{await Promise.allSettled([loadWeather(),loadData()]);finishRender()}catch(e){finishRender()}}
function renderLoading(){app.innerHTML=`<section class="screen loading"><div><div class="orbit"></div><h2>Dolcia prépare votre programme...</h2><p>Recherche de restaurants, concerts, théâtre, ateliers, marchés, activités et événements réels.</p><button class="outline" style="margin-top:20px" onclick="finishRender()">Voir l’agenda</button></div></section>`}
function finishRender(){S.loading=false;S.items=scoreAndFilter([...(S.places||[]),...(S.events||[])]);S.program=buildProgram(S.items);renderResults()}
async function api(path){const c=new AbortController();const t=setTimeout(()=>c.abort(),3000);try{let r=await fetch(path,{signal:c.signal});clearTimeout(t);let txt=await r.text();let d={};try{d=JSON.parse(txt)}catch{d={raw:txt}};if(!r.ok||d.error)throw new Error(d.error||r.statusText);return d}catch(e){clearTimeout(t);throw e}}
async function loadWeather(){try{S.weather=await api(`/api/weather?lat=${S.location.lat}&lng=${S.location.lng}`)}catch{}}
async function loadData(){let vibes=S.answers.vibes.length?S.answers.vibes:["food","culture","market","nature"];let calls=[];let seen=new Set();for(let v of vibes){for(let type of (TYPES[v]||[]).slice(0,3)){calls.push(api(`/api/places?lat=${S.location.lat}&lng=${S.location.lng}&radius=${S.radius}&type=${encodeURIComponent(type)}`).then(d=>addPlaces(d.results||[],seen)).catch(()=>{}))}for(let kw of (KW[v]||[]).slice(0,6)){calls.push(api(`/api/places?mode=text&lat=${S.location.lat}&lng=${S.location.lng}&radius=${S.radius}&keyword=${encodeURIComponent(kw+" "+S.location.name)}`).then(d=>addPlaces(d.results||[],seen)).catch(()=>{}))}}calls.push(api(`/api/events?lat=${S.location.lat}&lng=${S.location.lng}&radius=${Math.round(S.radius/1000)}&after=${fmt(S.start)}&before=${fmt(S.end)}&size=100`).then(d=>addEvents(d.events||d.results||[])).catch(()=>{}));await Promise.allSettled(calls)}
function fmt(d){return d.toISOString().split("T")[0]}
function addPlaces(list,seen){for(let p of list){if(!p.place_id||seen.has(p.place_id))continue;seen.add(p.place_id);let loc=p.geometry?.location||{};S.places.push({id:"g_"+p.place_id,kind:"place",source:"Google",name:p.name,address:p.vicinity||p.formatted_address||"",lat:loc.lat,lng:loc.lng,distance:loc.lat?dist(S.location.lat,S.location.lng,loc.lat,loc.lng):null,rating:p.rating||null,reviews:p.user_ratings_total||0,price:p.price_level??null,category:catFromTypes(p.types||[]),photoRef:p.photos?.[0]?.photo_reference||null,bookingUrl:null,types:p.types||[]})}}
function addEvents(list){for(let e of list){let title=text(e.title||e.ttl||e.name)||"Événement";let raw=JSON.stringify(e).toLowerCase();S.events.push({id:"oa_"+(e.uid||e.id||title),kind:"event",source:"OpenAgenda",name:title,address:text(e.location?.name||e.loc||e.location)||"",date:e.date||e.timings?.[0]?.begin||null,category:catFromText(raw),photoUrl:e.image||e.thumbnail||e.imageUrl||null,bookingUrl:e.registrationUrl||e.url||null,price:raw.includes("gratuit")?0:null})}}
function text(v){if(!v)return"";if(typeof v==="string")return v;if(typeof v==="object")return Object.values(v).join(" ");return String(v)}
function catFromTypes(t){let a=t.join(" ");if(/restaurant|cafe|bakery|bar/.test(a))return"food";if(/museum|art_gallery|movie_theater/.test(a))return"culture";if(/spa|beauty|swimming/.test(a))return"wellness";if(/bowling|amusement|aquarium|zoo|golf/.test(a))return"sport";if(/night|casino/.test(a))return"night";if(/park|tourist/.test(a))return"nature";return"culture"}
function catFromText(a){if(/concert|festival|théâtre|theatre|spectacle|humour|expo|cinéma|culture/.test(a))return"culture";if(/atelier|cours|leroy|cultura|ikea|stage/.test(a))return"workshop";if(/brocante|vide|marché|marche|foire|salon/.test(a))return"market";if(/restaurant|food|dégustation|brunch/.test(a))return"food";if(/spa|massage|yoga/.test(a))return"wellness";if(/sport|paddle|vélo|golf|bowling/.test(a))return"sport";if(/soirée|dj|bar|club/.test(a))return"night";return"culture"}
function scoreAndFilter(items){let bpp=perDayPerson();return items.map(x=>{let s=50;if(S.answers.vibes.includes(x.category))s+=25;if(x.kind==="event")s+=18;if(x.rating>=4.3)s+=12;if(x.reviews>80)s+=6;if(x.distance!=null&&x.distance<5)s+=8;if(x.bookingUrl)s+=6;if(bpp!==null&&x.price!==null){if(bpp<20&&x.price>1)s-=20;if(bpp>60&&x.price>=2)s+=5}return{...x,score:s}}).sort((a,b)=>b.score-a.score).slice(0,80)}
function buildProgram(items){if(!items.length)return[];let days=daysCount(),slots=[];for(let d=1;d<=Math.min(days,7);d++){if(days>1)slots.push(`Jour ${d} matin`,`Jour ${d} midi`,`Jour ${d} après-midi`,`Jour ${d} apéritif`,`Jour ${d} soir`);else slots=["Matin","Midi","Après-midi","Apéritif","Soirée"]}let used=new Set(),cats=[];return slots.map((slot,i)=>{let pref=prefCats(slot);let pick=items.find(x=>!used.has(x.id)&&pref.includes(x.category)&&x.category!==cats[cats.length-1])||items.find(x=>!used.has(x.id)&&pref.includes(x.category))||items.find(x=>!used.has(x.id)&&x.category!==cats[cats.length-1])||items.find(x=>!used.has(x.id));if(pick){used.add(pick.id);cats.push(pick.category)}return pick?{slot,item:pick}:null}).filter(Boolean)}
function prefCats(slot){let s=slot.toLowerCase();if(s.includes("midi"))return["food"];if(s.includes("apéritif"))return["night","food","nature"];if(s.includes("soir"))return["culture","night","food"];if(s.includes("matin"))return["market","culture","nature","workshop"];if(s.includes("après"))return["sport","wellness","workshop","culture","nature"];return["food","culture","market","nature","wellness","sport","night"]}
function renderResults(){let days=groupDays(),active=S.activeDay in days?S.activeDay:Object.keys(days)[0]||"Jour 1";S.activeDay=active;app.innerHTML=`<section class="screen"><div class="scroll">${top(false)}<div class="inner result-head"><div class="eyebrow">Agenda concierge</div><h2>${S.program.length?"Votre programme.":"Je continue la recherche."}</h2><p>${nice(S.start)}${same(S.start,S.end)?"":" → "+nice(S.end)} · ${S.location.name} · ${budgetText()}</p><div class="chips">${chipData().map(c=>`<span class="chip">${c}</span>`).join("")}</div></div>${Object.keys(days).length>1?`<div class="daytabs">${Object.keys(days).map(d=>`<button class="daytab ${d===active?'sel':''}" onclick="S.activeDay='${d}';renderResults()">${d}</button>`).join("")}</div>`:""}<div class="summarybar">${S.program.length?"Dolcia varie les catégories pour éviter les programmes répétitifs. Chaque proposition vient d’une source réelle.":"Aucune activité réelle n’a encore remonté. Dolcia n’invente rien."}</div>${S.program.length?`<div class="agenda">${(days[active]||[]).map((s,i)=>slotHtml(s,i)).join("")}</div>`:emptyHtml()}${S.items.length?`<div class="inner" style="padding-top:10px"><h3>Autres idées</h3></div><div class="agenda">${S.items.slice(0,12).map((x,i)=>itemHtml(x,"Suggestion",i,true)).join("")}</div>`:""}</div><nav class="bottom"><button class="sel" onclick="renderResults()">Agenda</button><button onclick="go('where')">Composer</button><button onclick="renderMyAgenda()">Mes sorties</button></nav><div id="detail" class="detail"></div></section>`}
function groupDays(){let out={};S.program.forEach((s,i)=>{let m=String(s.slot).match(/Jour \d+/);let d=m?m[0]:"Aujourd’hui";if(!out[d])out[d]=[];out[d].push({...s,idx:i})});return out}
function chipData(){return [S.answers.who==="family"?"Famille":S.answers.who==="couple"?"Couple":S.answers.who==="friends"?"Amis":"Solo",...S.answers.vibes.slice(0,4).map(v=>VIBES.find(x=>x[0]===v)?.[1]||v)]}
function slotHtml(s,i){return `<div><div class="slot-label">${s.slot}</div>${itemHtml(s.item,s.slot,s.idx,false)}</div>`}
function itemHtml(x,label,i,suggestion=false){return `<article class="item" onclick="openDetail('${x.id}')"><div class="img" style="background-image:url('${photo(x)}')"></div><div><div class="meta"><span>${x.source}</span><span>${catLabel(x.category)}</span>${x.distance?`<span>${x.distance.toFixed(1)} km</span>`:""}${x.rating?`<span>★ ${Number(x.rating).toFixed(1)}</span>`:""}</div><h4>${esc(x.name)}</h4><p>${why(x)}</p><div class="acts" onclick="event.stopPropagation()">${suggestion?`<button onclick="addAgenda('${x.id}')">Agenda</button>`:`<button onclick="validateSlot(${i})" class="${S.agenda.find(a=>a.id===x.id)?'ok':''}">Valider</button><button onclick="regen(${i})">Changer</button>`}<button class="${x.bookingUrl?'book':''}" onclick="${x.bookingUrl?`book('${x.id}')`:`toast('Réservation bientôt disponible')`}">${x.bookingUrl?'Réserver':'Bientôt'}</button></div></div></article>`}
function catLabel(c){return {food:"Gastro",culture:"Culture",workshop:"Atelier",market:"Marché",nature:"Nature",wellness:"Bien-être",sport:"Loisir",night:"Sortir"}[c]||"Idée"}
function why(x){if(x.kind==="event")return"Événement réel disponible aux dates choisies.";if(x.category==="food")return"Pause gourmande pour structurer la journée.";if(x.category==="culture")return"Ajoute une vraie découverte au programme.";if(x.category==="market")return"Idée locale souvent oubliée par les recherches classiques.";if(x.category==="workshop")return"Expérience manuelle ou créative pour changer des sorties classiques.";if(x.category==="nature")return"Respiration extérieure intégrée sans répéter toute la journée.";return"Choisi pour diversifier le programme."}
function emptyHtml(){return `<div class="empty"><h3>Aucune activité réelle.</h3><p>Élargissez le rayon ou vérifiez les API. L’application ne bloque pas et n’invente rien.</p><button class="gold" onclick="S.radius+=15000;compose()">Élargir</button></div>`}
function validateSlot(i){let s=S.program[i];if(!s)return;addAgenda(s.item.id);renderResults()}
function addAgenda(id){let x=S.items.find(i=>i.id===id)||S.program.map(p=>p.item).find(i=>i.id===id);if(x&&!S.agenda.find(a=>a.id===id)){S.agenda.push({...x,addedAt:new Date().toISOString()});save()}toast("Ajouté à Mon Agenda Dolcia")}
function regen(i){let current=S.program[i];if(!current)return;let used=new Set(S.program.map((p,j)=>j===i?null:p.item.id).filter(Boolean));let pref=prefCats(current.slot);let pick=S.items.find(x=>!used.has(x.id)&&pref.includes(x.category)&&x.id!==current.item.id)||S.items.find(x=>!used.has(x.id)&&x.id!==current.item.id);if(pick){S.program[i]={slot:current.slot,item:pick};renderResults()}else toast("Pas d’autre activité réelle disponible")}
function renderMyAgenda(){app.innerHTML=`<section class="screen"><div class="scroll">${top(false)}<div class="inner result-head"><div class="eyebrow">Mon Agenda Dolcia</div><h2>Vos sorties.</h2><p>Activités validées, à retrouver et noter.</p></div>${S.agenda.length?`<div class="agenda">${S.agenda.map((x,i)=>itemHtml(x,"Agenda",i,true)).join("")}</div>`:emptyHtml()}</div><nav class="bottom"><button onclick="renderResults()">Agenda</button><button onclick="go('where')">Composer</button><button class="sel" onclick="renderMyAgenda()">Mes sorties</button></nav><div id="detail" class="detail"></div></section>`}
function openDetail(id){let x=S.items.find(i=>i.id===id)||S.agenda.find(i=>i.id===id)||S.program.map(p=>p.item).find(i=>i.id===id);if(!x)return;document.getElementById("detail").innerHTML=`<div class="scroll"><div class="detail-photo" style="background-image:url('${photo(x)}')"></div><button class="icon" style="position:fixed;z-index:99;top:18px;left:18px" onclick="closeDetail()">←</button><div class="detail-card"><div class="eyebrow">${x.source} · ${catLabel(x.category)}</div><h2>${esc(x.name)}</h2><p>${why(x)}</p><p>${esc(x.address||"Adresse non fournie par la source")}</p><div style="display:grid;gap:9px;margin-top:15px"><button class="gold" onclick="addAgenda('${x.id}')">Ajouter à mon agenda</button><button class="outline" onclick="${x.bookingUrl?`book('${x.id}')`:`toast('Réservation bientôt disponible chez les partenaires Dolcia')`}">${x.bookingUrl?'Réserver':'Réserver bientôt'}</button></div></div></div>`;document.getElementById("detail").classList.add("open")}
function closeDetail(){document.getElementById("detail").classList.remove("open")}
function photo(x){if(x.photoUrl)return x.photoUrl;if(x.photoRef)return `/api/photo?ref=${encodeURIComponent(x.photoRef)}&maxwidth=900`;return IMG[x.category]||IMG.fallback}
function book(id){let x=S.items.find(i=>i.id===id)||S.agenda.find(i=>i.id===id);if(x?.bookingUrl)window.open(x.bookingUrl,"_blank")}
function toast(msg){let e=document.createElement("div");e.textContent=msg;e.style.cssText="position:fixed;z-index:999;left:50%;bottom:95px;transform:translateX(-50%);background:rgba(5,5,8,.92);border:1px solid rgba(255,255,255,.15);border-radius:999px;padding:12px 18px;color:white;font-size:13px";document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
function dist(a,b,c,d){let R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180;let q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
renderHome();
