const proApp=document.querySelector('#proApp');
const partnerState={view:'overview',online:localStorage.getItem('dolcia_partner_online')==='true',push:JSON.parse(localStorage.getItem('dolcia_partner_push')||'{"mission":true,"changes":true,"urgent":true,"documents":true}')};
const views={
  overview:{label:'Vue d’ensemble',title:'Votre activité, orchestrée.',copy:'Pilotez votre visibilité, vos missions et la qualité de votre présence dans Dolcia.'},
  missions:{label:'Missions',title:'Les bonnes missions. Au bon moment.',copy:'Seules les demandes compatibles avec vos services, votre zone et vos disponibilités apparaîtront.'},
  publish:{label:'Publications',title:'Donnez envie, avec du réel.',copy:'Événements et offres vérifiés avant diffusion auprès des voyageurs pertinents.'},
  availability:{label:'Disponibilités',title:'Votre temps vous appartient.',copy:'Ouvrez précisément les créneaux où vous souhaitez recevoir des demandes.'},
  reputation:{label:'Qualité & avis',title:'La confiance se construit.',copy:'Suivez les notes, retours clients, documents et actions d’amélioration.'},
  notifications:{label:'Alertes push',title:'Seulement ce qui compte.',copy:'Choisissez les alertes indispensables à votre activité.'}
};
function render(){const current=views[partnerState.view];proApp.innerHTML=`<div class="pro-shell"><aside class="pro-nav"><div class="logo">dolc<i>ia</i></div><small>Espace partenaires</small>${Object.entries(views).map(([id,v])=>`<button class="${partnerState.view===id?'active':''}" onclick="openView('${id}')">${v.label}</button>`).join('')}<a href="/">← Retour à Dolcia</a></aside><main class="pro-main"><header class="partner-top"><div><span class="eyebrow">Le Touquet · Programme pilote</span><h1>${current.title}</h1><p class="lead">${current.copy}</p></div><div class="partner-presence"><span>${partnerState.online?'Disponible':'Hors ligne'}</span><button class="switch ${partnerState.online?'on':''}" onclick="toggleOnline()"><i></i></button></div></header>${viewContent()}</main><nav class="partner-mobile-nav">${['overview','missions','publish','notifications'].map(id=>`<button class="${partnerState.view===id?'active':''}" onclick="openView('${id}')">${views[id].label}</button>`).join('')}</nav></div>`}
function viewContent(){if(partnerState.view==='overview')return overview();if(partnerState.view==='missions')return missions();if(partnerState.view==='publish')return publish();if(partnerState.view==='availability')return availability();if(partnerState.view==='reputation')return reputation();return notifications()}
function notificationPermission(){return 'Notification'in window?Notification.permission:'unsupported'}
function overview(){return `<section class="metrics"><article class="metric"><span>Vues qualifiées</span><b>—</b><small>Dès la première diffusion</small></article><article class="metric"><span>Ajouts à l’agenda</span><b>—</b><small>Intention forte</small></article><article class="metric"><span>Réservations</span><b>—</b><small>Liens vérifiés</small></article><article class="metric"><span>Note partenaire</span><b>—</b><small>Après prestation</small></article></section><div class="grid"><section class="panel mission-preview"><div class="panel-head"><div><span class="eyebrow">Temps réel</span><h2>Boîte de missions</h2></div><button onclick="openView('missions')">Tout voir</button></div><div class="true-empty"><b>Aucune mission pour le moment</b><span>Passez disponible pour recevoir uniquement les demandes compatibles.</span></div></section><section class="panel"><span class="eyebrow">À faire</span><h2>Prêt pour l’ouverture</h2><div class="readiness"><div><span>Identité et entreprise</span><b>À vérifier</b></div><div><span>Assurance</span><b>À fournir</b></div><div><span>Zone d’intervention</span><b>À définir</b></div><div><span>Notifications</span><b>${notificationPermission()==='granted'?'Activées':'À configurer'}</b></div></div></section></div>`}
function missions(){return `<div class="mission-layout"><section class="panel"><div class="panel-head"><div><span class="eyebrow">Demandes compatibles</span><h2>Nouvelles missions</h2></div><span class="live-dot ${partnerState.online?'on':''}">${partnerState.online?'Écoute active':'En pause'}</span></div><div class="true-empty tall"><b>Votre boîte est vide</b><span>Aucune fausse mission n’est affichée. Les demandes réelles arriveront ici après validation de votre compte.</span><button onclick="toggleOnline()">${partnerState.online?'Me rendre indisponible':'Me rendre disponible'}</button></div></section><aside class="panel mission-rules"><h2>Pourquoi cette mission ?</h2><p>Chaque demande doit correspondre à votre service, vos qualifications, votre rayon, votre créneau et votre capacité.</p><div class="trust">Une mission urgente n’est jamais envoyée à un prestataire non vérifié.</div></aside></div>`}
function publish(){return `<div class="publish-grid"><button class="publish-card gold" onclick="draft('event')"><span>01</span><h2>Créer un événement</h2><p>Animation, atelier, soirée, concert, menu spécial ou expérience privée.</p><b>Commencer →</b></button><button class="publish-card" onclick="draft('offer')"><span>02</span><h2>Créer une offre</h2><p>Prix, quantité, période et conditions obligatoires. Rien d’inventé.</p><b>Commencer →</b></button><button class="publish-card" onclick="draft('service')"><span>03</span><h2>Proposer un service</h2><p>Babysitting, chauffeur, ménage, conciergerie, livraison ou réservation.</p><b>Commencer →</b></button></div><section class="panel publication-list"><h2>Vos publications</h2><div class="true-empty"><b>Aucune publication</b><span>Vos brouillons, contenus en validation et publications actives apparaîtront ici.</span></div></section>`}
function availability(){return `<div class="grid"><section class="panel"><span class="eyebrow">Semaine type</span><h2>Quand êtes-vous disponible ?</h2><div class="week-grid">${['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(day=>`<button onclick="this.classList.toggle('selected')"><b>${day}</b><span>Ajouter un créneau</span></button>`).join('')}</div></section><section class="panel"><h2>Zone d’intervention</h2><p>Le rayon sera contrôlé strictement. Vous ne recevrez aucune mission à Calais si votre zone est Le Touquet.</p><div class="zone-chip">Le Touquet · à définir</div></section></div>`}
function reputation(){return `<section class="metrics"><article class="metric"><span>Note moyenne</span><b>—</b></article><article class="metric"><span>Missions terminées</span><b>0</b></article><article class="metric"><span>Taux d’acceptation</span><b>—</b></article><article class="metric"><span>Incidents</span><b>0</b></article></section><div class="grid"><section class="panel"><h2>Avis clients</h2><div class="true-empty"><b>Pas encore d’avis</b><span>Seuls les clients ayant réellement terminé une prestation pourront noter.</span></div></section><section class="panel"><h2>Conformité</h2><div class="readiness"><div><span>Statut</span><b>Candidature</b></div><div><span>Révision humaine</span><b>Requise</b></div><div><span>Documents</span><b>Non transmis</b></div></div></section></div>`}
function notifications(){const labels={mission:['Nouvelles missions','Demande compatible avec votre profil et votre disponibilité.'],changes:['Modifications et annulations','Horaire, adresse ou statut d’une mission acceptée.'],urgent:['Demandes urgentes','Uniquement si vous avez activé la disponibilité immédiate.'],documents:['Confiance et documents','Pièce expirante, complément ou décision de validation.']};return `<div class="grid"><section class="panel"><span class="eyebrow">Consentement détaillé</span><h2>Vos alertes</h2><div class="push-list">${Object.entries(labels).map(([id,text])=>`<label><div><b>${text[0]}</b><span>${text[1]}</span></div><input type="checkbox" ${partnerState.push[id]?'checked':''} onchange="setPush('${id}',this.checked)"></label>`).join('')}</div><button class="push-enable" onclick="enablePush()">${notificationPermission()==='granted'?'Notifications autorisées':'Autoriser les notifications sur cet appareil'}</button></section><section class="panel"><h2>Règle anti-spam</h2><p>Pas de publicité générale. Pas de mission hors zone. Pas de push si vous êtes indisponible.</p><div class="trust">Une notification doit permettre une action utile et immédiate. Sinon, elle n’est pas envoyée.</div></section></div>`}
function openView(id){partnerState.view=id;render()}function toggleOnline(){partnerState.online=!partnerState.online;localStorage.setItem('dolcia_partner_online',partnerState.online);render()}function setPush(id,value){partnerState.push[id]=value;localStorage.setItem('dolcia_partner_push',JSON.stringify(partnerState.push))}async function enablePush(){if(!('Notification'in window))return alert('Notifications non disponibles sur cet appareil.');const permission=await Notification.requestPermission();if(permission==='granted'&&'serviceWorker'in navigator)await navigator.serviceWorker.register('/sw.js');render()}function draft(type){localStorage.setItem('dolcia_partner_draft',JSON.stringify({type,createdAt:new Date().toISOString()}));alert('Brouillon créé. La publication sera possible après authentification et validation du partenaire.')}render();
