const proApp=document.querySelector('#proApp');
const saved=JSON.parse(localStorage.getItem('dolcia_partner_workspace')||'null');
const partnerState=saved||{view:'welcome',authenticated:false,status:'draft',company:{name:'',email:'',siret:'',contact:'',type:''},establishments:[],publications:[],contract:{status:'not_started'},online:false};
const views={overview:'Vue d’ensemble',onboarding:'Candidature & contrat',places:'Établissements',publish:'Programmes & événements',offers:'Offres flash',availability:'Disponibilités',quality:'Qualité des données'};
function save(){localStorage.setItem('dolcia_partner_workspace',JSON.stringify(partnerState))}
function esc(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function openView(id){partnerState.view=id;save();render()}
function render(){if(!partnerState.authenticated)return renderGate();const current=views[partnerState.view]||views.overview;proApp.innerHTML=`<div class="pro-shell"><aside class="pro-nav"><div class="logo">dolc<i>ia</i></div><small>Espace partenaire privé</small>${Object.entries(views).map(([id,label])=>`<button class="${partnerState.view===id?'active':''}" onclick="openView('${id}')">${label}</button>`).join('')}<a href="/">← Quitter l’espace privé</a></aside><main class="pro-main"><header class="partner-top"><div><span class="eyebrow">${esc(partnerState.company.name||'Candidature Dolcia')}</span><h1>${current}</h1><p class="lead">${statusCopy()}</p></div><span class="status-pill status-${partnerState.status}">${statusLabel()}</span></header>${viewContent()}</main></div>`}
function renderGate(){proApp.innerHTML=`<main class="partner-gate"><section><div class="logo">dolc<i>ia</i></div><span class="eyebrow">Portail strictement réservé aux professionnels</span><h1>Faites vivre votre territoire.<br><em>Dolcia trouve votre public.</em></h1><p>Créez votre compte professionnel, faites valider votre entreprise puis signez votre contrat. L’espace de gestion n’est jamais accessible depuis l’application client.</p><div class="gate-actions"><button onclick="startApplication()">Devenir partenaire</button><button class="secondary" onclick="loginPartner()">J’ai déjà un compte</button></div><small>Une candidature n’est jamais publiée automatiquement. L’équipe Dolcia contrôle l’identité, l’établissement et les informations proposées.</small></section><aside><span>Le parcours</span><ol><li><b>01</b>Compte professionnel</li><li><b>02</b>Vérification de l’entreprise</li><li><b>03</b>Contrat électronique</li><li><b>04</b>Activation de l’espace privé</li><li><b>05</b>Publications contrôlées</li></ol></aside></main>`}
function startApplication(){partnerState.authenticated=true;partnerState.view='onboarding';partnerState.status='draft';save();render()}
function loginPartner(){const email=prompt('Adresse e-mail professionnelle');if(!email)return;partnerState.authenticated=true;partnerState.company.email=email;partnerState.view=partnerState.status==='approved'?'overview':'onboarding';save();render()}
function statusLabel(){return({draft:'Brouillon',submitted:'En vérification',changes:'Complément demandé',contract:'Contrat à signer',approved:'Compte activé'}[partnerState.status]||'Candidature')}
function statusCopy(){if(partnerState.status==='approved')return'Gérez vos établissements et publiez uniquement des informations exactes, datées et vérifiables.';return'Votre espace de gestion sera activé après vérification humaine et signature du contrat.'}
function viewContent(){return({overview, onboarding, places, publish, offers, availability, quality}[partnerState.view]||overview)()}
function overview(){return `<section class="metrics"><article><span>Établissements</span><b>${partnerState.establishments.length}</b></article><article><span>Publications</span><b>${partnerState.publications.length}</b></article><article><span>À contrôler</span><b>${partnerState.publications.filter(p=>p.status==='draft').length}</b></article><article><span>Statut</span><b>${statusLabel()}</b></article></section><div class="grid"><section class="panel"><span class="eyebrow">Action prioritaire</span><h2>${partnerState.status==='approved'?'Votre présence est prête.':'Finalisez votre candidature.'}</h2><p>${partnerState.status==='approved'?'Ajoutez vos événements, programmes saisonniers, horaires et offres de dernière minute.':'Dolcia doit connaître l’entreprise, le signataire et chaque établissement avant toute publication.'}</p><button onclick="openView('${partnerState.status==='approved'?'publish':'onboarding'}')">Continuer →</button></section><section class="panel"><span class="eyebrow">Règle Dolcia</span><h2>La pertinence avant la publicité.</h2><p>Un partenaire payant ne remonte avant un autre qu’à pertinence égale. Une information incomplète ou douteuse est bloquée.</p></section></div>`}
function onboarding(){const c=partnerState.company;return `<section class="journey"><article class="${c.name&&c.email?'done':'active'}"><b>01</b><div><h3>Compte et entreprise</h3><p>Identité légale, SIRET et personne habilitée à signer.</p></div></article><article class="${partnerState.status==='submitted'?'active':['contract','approved'].includes(partnerState.status)?'done':''}"><b>02</b><div><h3>Vérification Dolcia</h3><p>Contrôle humain de l’entreprise, des justificatifs et du territoire.</p></div></article><article class="${partnerState.status==='contract'?'active':partnerState.status==='approved'?'done':''}"><b>03</b><div><h3>Contrat électronique</h3><p>Conditions, responsabilités, données, durée, résiliation et autorisation de publication.</p></div></article><article class="${partnerState.status==='approved'?'done':''}"><b>04</b><div><h3>Activation privée</h3><p>Le professionnel reçoit son accès nominatif et ses droits.</p></div></article></section><section class="panel form-panel"><span class="eyebrow">Dossier partenaire</span><h2>Qui souhaitez-vous référencer ?</h2><div class="form-grid"><label>Raison sociale<input id="legalName" value="${esc(c.name)}" placeholder="Ex. Parc Bagatelle"></label><label>E-mail professionnel<input id="companyEmail" type="email" value="${esc(c.email)}"></label><label>SIRET<input id="siret" value="${esc(c.siret)}" inputmode="numeric"></label><label>Signataire habilité<input id="contact" value="${esc(c.contact)}"></label><label>Type d’activité<select id="companyType"><option>Parc de loisirs</option><option>Office de tourisme</option><option>Restaurant</option><option>Hébergement</option><option>Prestataire d’activités</option><option>Lieu culturel</option><option>Service de conciergerie</option></select></label><label>Territoire principal<input id="territory" placeholder="Le Touquet / Côte d’Opale"></label></div><div class="document-row"><button>Déposer un extrait d’immatriculation</button><button>Déposer une assurance</button><button>Déposer une pièce du signataire</button></div><div class="form-actions"><button onclick="saveApplication()">Enregistrer</button><button class="primary" onclick="submitApplication()">Envoyer pour validation</button>${partnerState.status==='contract'?'<button class="primary" onclick="signContract()">Lire et signer le contrat</button>':''}</div><p class="legal-note">La signature finale devra passer par un prestataire de signature électronique qualifié. Dolcia conservera la version, l’horodatage et l’identité du signataire.</p></section>`}
function readApplication(){partnerState.company={name:document.querySelector('#legalName')?.value.trim(),email:document.querySelector('#companyEmail')?.value.trim(),siret:document.querySelector('#siret')?.value.trim(),contact:document.querySelector('#contact')?.value.trim(),type:document.querySelector('#companyType')?.value}}
function saveApplication(){readApplication();save();toast('Dossier enregistré')}
function submitApplication(){readApplication();if(!partnerState.company.name||!partnerState.company.email||!partnerState.company.siret||!partnerState.company.contact)return toast('Complétez les quatre informations obligatoires');partnerState.status='submitted';save();render();toast('Candidature envoyée à l’équipe Dolcia')}
function signContract(){partnerState.contract={status:'signed',signedAt:new Date().toISOString(),signer:partnerState.company.contact};partnerState.status='approved';save();render();toast('Contrat signé — compte partenaire activé')}
function places(){return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">Lieux vérifiés</span><h2>Vos établissements</h2></div><button onclick="addPlace()">+ Ajouter un établissement</button></div>${partnerState.establishments.length?`<div class="data-list">${partnerState.establishments.map((place,index)=>`<article><div><span>${esc(place.type)}</span><h3>${esc(place.name)}</h3><p>${esc(place.address)}</p></div><button onclick="editPlace(${index})">Mettre à jour</button></article>`).join('')}</div>`:'<div class="true-empty"><b>Aucun établissement</b><span>Ajoutez le lieu exact avant de publier un événement ou une offre.</span></div>'}</section>`}
function addPlace(){if(partnerState.status!=='approved')return toast('Le compte doit être validé avant cet ajout');const name=prompt('Nom public de l’établissement');if(!name)return;const address=prompt('Adresse complète');if(!address)return;const type=prompt('Type de lieu (parc, restaurant, hôtel, activité…)')||'Lieu de loisirs';partnerState.establishments.push({name,address,type,status:'pending'});save();render()}
function editPlace(index){const place=partnerState.establishments[index];const address=prompt('Adresse complète',place.address);if(address){place.address=address;place.updatedAt=new Date().toISOString();save();render()}}
function publish(){return `<div class="publish-grid"><button class="publish-card gold" onclick="createPublication('program')"><span>01</span><h2>Créer un programme</h2><p>Festival, saison, vacances scolaires ou série d’animations avec plusieurs rendez-vous.</p><b>Commencer →</b></button><button class="publish-card" onclick="createPublication('event')"><span>02</span><h2>Créer un événement</h2><p>Une date, un horaire, une adresse et une fiche complète obligatoires.</p><b>Commencer →</b></button><button class="publish-card" onclick="createPublication('recurring')"><span>03</span><h2>Créer une série</h2><p>Atelier récurrent, spectacle hebdomadaire ou activité saisonnière.</p><b>Commencer →</b></button></div><section class="panel"><h2>Vos publications</h2>${publicationList()}</section>`}
function createPublication(type){if(partnerState.status!=='approved')return toast('Finalisez d’abord la validation et le contrat');if(!partnerState.establishments.length)return toast('Ajoutez d’abord l’établissement concerné');const title=prompt(type==='program'?'Nom du programme ou festival':'Nom de l’événement');if(!title)return;const starts=prompt('Date et heure de début (AAAA-MM-JJ HH:MM)');if(!starts)return;partnerState.publications.push({id:Date.now(),type,title,starts,place:partnerState.establishments[0].name,status:'draft',occurrences:type==='program'?[]:null});save();render();toast('Brouillon créé — complétez les dates avant envoi')}
function publicationList(){if(!partnerState.publications.length)return'<div class="true-empty"><b>Aucune publication</b><span>Les programmes, événements et séries apparaîtront ici avec leur état de validation.</span></div>';return `<div class="data-list">${partnerState.publications.map((item,index)=>`<article><div><span>${item.type==='program'?'Programme multi-événements':item.type==='recurring'?'Série récurrente':'Événement'} · ${esc(item.status)}</span><h3>${esc(item.title)}</h3><p>${esc(item.starts)} · ${esc(item.place)}</p></div><button onclick="submitPublication(${index})">Envoyer au contrôle</button></article>`).join('')}</div>`}
function submitPublication(index){partnerState.publications[index].status='pending';save();render();toast('Publication envoyée au moteur de vérité Dolcia')}
function offers(){return `<section class="panel"><span class="eyebrow">Remplissage intelligent</span><h2>Offres de dernière minute</h2><p>Une offre n’est acceptée que si le prix Dolcia est réellement inférieur au prix public, avec quantité et expiration vérifiables.</p><button onclick="createOffer()">Créer une offre flash</button></section><section class="rules"><article><b>Prix public</b><span>Obligatoire et prouvable</span></article><article><b>Prix Dolcia</b><span>Strictement inférieur</span></article><article><b>Stock</b><span>Quantité restante en temps réel</span></article><article><b>Fin</b><span>Expiration automatique</span></article></section>`}
function createOffer(){if(partnerState.status!=='approved')return toast('Compte partenaire non activé');toast('Le formulaire d’offre sera relié à la réservation et au stock partenaire')}
function availability(){return `<section class="panel"><span class="eyebrow">Synchronisation</span><h2>Horaires et disponibilités</h2><p>Importez vos horaires habituels, fermetures exceptionnelles, capacités et créneaux disponibles. Une information expirée est automatiquement déclassée.</p><div class="document-row"><button>Connecter un agenda</button><button>Importer un fichier</button><button>Déclarer une fermeture</button></div></section>`}
function quality(){return `<section class="panel"><span class="eyebrow">Moteur de vérité</span><h2>Ce que Dolcia contrôle avant publication</h2><div class="quality-grid">${['Adresse géolocalisée','Date et horaire compatibles','Photo réellement liée au lieu','Lien de réservation actif','Prix et conditions','Doublons nationaux','Cohérence catégorie/activité','Actualité de l’information'].map(item=>`<article><b>✓</b><span>${item}</span></article>`).join('')}</div><p>Une publication douteuse reste privée. L’intelligence artificielle détecte les contradictions ; une équipe humaine tranche les cas sensibles.</p></section>`}
function toast(message){let node=document.querySelector('.pro-toast');if(!node){node=document.createElement('div');node.className='pro-toast';document.body.appendChild(node)}node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2600)}
render();
