export const DECISION_CODES_VERSION = '1.0.3';

export const DECISION_CODES = Object.freeze({
  TRAVEL_COMPATIBLE_WITH_DURATION: 'TRAVEL_COMPATIBLE_WITH_DURATION',
  TRAVEL_INCOMPATIBLE_WITH_DURATION: 'TRAVEL_INCOMPATIBLE_WITH_DURATION',
  TRAVEL_TIME_UNAVAILABLE: 'TRAVEL_TIME_UNAVAILABLE',
  HIGH_RARITY: 'HIGH_RARITY',
  LOW_RARITY: 'LOW_RARITY',
  RARITY_UNVERIFIED: 'RARITY_UNVERIFIED',
  NO_CORE_EQUIVALENT: 'NO_CORE_EQUIVALENT',
  CORE_EQUIVALENT_EXISTS: 'CORE_EQUIVALENT_EXISTS',
  BETTER_REGIONAL_ALTERNATIVE_EXISTS: 'BETTER_REGIONAL_ALTERNATIVE_EXISTS',
  NEARBY_COMPLEMENT: 'NEARBY_COMPLEMENT',
  HOURS_COMPATIBLE: 'HOURS_COMPATIBLE',
  HOURS_INCOMPATIBLE: 'HOURS_INCOMPATIBLE',
  HOURS_UNKNOWN: 'HOURS_UNKNOWN',
  CLOSED_PERMANENTLY: 'CLOSED_PERMANENTLY',
  DATE_INCOMPATIBLE: 'DATE_INCOMPATIBLE',
  AUDIENCE_INCOMPATIBLE: 'AUDIENCE_INCOMPATIBLE',
  COORDINATES_RELIABLE: 'COORDINATES_RELIABLE',
  COORDINATES_USABLE_APPROXIMATE: 'COORDINATES_USABLE_APPROXIMATE',
  COORDINATES_UNRELIABLE: 'COORDINATES_UNRELIABLE',
  ADMIN_COMPONENTS_INCOMPLETE: 'ADMIN_COMPONENTS_INCOMPLETE',
  USER_WIDENED_SEARCH: 'USER_WIDENED_SEARCH',
  DEFAULT_SCOPE: 'DEFAULT_SCOPE',
  CATEGORY_SCOPE_NARROW: 'CATEGORY_SCOPE_NARROW',
  CATEGORY_SCOPE_WIDE: 'CATEGORY_SCOPE_WIDE',
  CATEGORY_MISMATCH: 'CATEGORY_MISMATCH',
  SOURCE_EVIDENCE_MISSING: 'SOURCE_EVIDENCE_MISSING',
  EVIDENCE_VALID: 'EVIDENCE_VALID',
  EVIDENCE_MISSING: 'EVIDENCE_MISSING',
  EVIDENCE_STALE: 'EVIDENCE_STALE',
  EVIDENCE_UNTRUSTED_SOURCE: 'EVIDENCE_UNTRUSTED_SOURCE'
});

export const DECISION_CODE_SET = new Set(Object.values(DECISION_CODES));

export const CODE_FAMILIES = Object.freeze({
  travel: ['TRAVEL_COMPATIBLE_WITH_DURATION', 'TRAVEL_INCOMPATIBLE_WITH_DURATION', 'TRAVEL_TIME_UNAVAILABLE'],
  rarity: ['HIGH_RARITY', 'LOW_RARITY', 'RARITY_UNVERIFIED'],
  alternative: ['NO_CORE_EQUIVALENT', 'CORE_EQUIVALENT_EXISTS', 'BETTER_REGIONAL_ALTERNATIVE_EXISTS'],
  hours: ['HOURS_COMPATIBLE', 'HOURS_INCOMPATIBLE', 'HOURS_UNKNOWN'],
  location: ['COORDINATES_RELIABLE', 'COORDINATES_USABLE_APPROXIMATE', 'COORDINATES_UNRELIABLE'],
  scope: ['USER_WIDENED_SEARCH', 'DEFAULT_SCOPE'],
  category: ['CATEGORY_SCOPE_NARROW', 'CATEGORY_SCOPE_WIDE'],
  evidence: ['EVIDENCE_VALID', 'EVIDENCE_MISSING', 'EVIDENCE_STALE', 'EVIDENCE_UNTRUSTED_SOURCE']
});

export function validateDecisionCodes(codes = []) {
  const unknown = codes.filter(code => !DECISION_CODE_SET.has(code));
  const contradictions = [];
  for (const [family, members] of Object.entries(CODE_FAMILIES)) {
    const present = members.filter(code => codes.includes(code));
    if (present.length > 1) contradictions.push({ family, codes: present });
  }
  return { valid: unknown.length === 0 && contradictions.length === 0, unknown, contradictions };
}
